services:
  cicd_server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cicd_server
    networks:
      - cicd-network
    ports:
      - "4002:4002" 
    expose:
      - 4002
 #   environment:
 #    - NODE_ENV=production
  #    - PORT=4002
    volumes:
   #   - ./cicd_server:/usr/src/app
    - ./backend:/usr/src/app

      - /usr/src/app/node_modules
    restart: unless-stopped

  cicd_nginx:
    image: nginx:alpine
    #build:
     # context: ./nginx
      #dockerfile: Dockerfile
    container_name: cicd_nginx
    networks:
      - cicd-network
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - 8080
 #   environment:
 #     - NODE_ENV=production
    depends_on:
      - cicd_server
    restart: unless-stopped

networks:
  cicd-network:
    name: cicd-network
    external: true
